### ISSUE TITLE
Game still running after opening Menu/Map

### ISSUE THREAD

**Issue by LimaXII** [petcomputacaoufrgs/raposa#1]
After opening the Menu or Map the character can still look up, down, left and right (with W,S,A,D or arrows), this means the game is still running...

![image](https://user-images.githubusercontent.com/85250416/166977576-5eb3073d-11a8-44d9-89a2-88f6127ee0a4.png)

Just pressed 'A' and the character start looking to the other side.

![image](https://user-images.githubusercontent.com/85250416/166977619-8e26b70e-c5ee-4086-9e71-58806271147c.png)

 Same applies to all other directions.

The other problem is with the objects, even with the Menu open, you can still interact with objects in the game.

Menu open.
![image](https://user-images.githubusercontent.com/85250416/166978092-805107f5-cba9-488e-9b56-ea5b3909f7aa.png)

After press "fire1" with the menu open.
![image](https://user-images.githubusercontent.com/85250416/166978159-ca760a74-22bb-4073-99bd-95b6ffa042a8.png)

**Comment by matheusalsi** [comment]
Here's some explanation

Basically when the game is paused, TimeScale is set to 0 so the game technically stops running. However not everything is affected and update will continue to be called, in this case control input and destroy object scripts updates needs a conditional control to work properly. Thankfuly our public static bool GameIsPaused can be easily used to fix that.

Hopefully any problem related was solved in the last commit i just made it.
 
Great issue! Thanks a lot

Bellow i'll leave a link about this topic
https://gamedevbeginner.com/the-right-way-to-pause-the-game-in-unity/
